# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build SSHJ


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java9:
    name: Build with Java 9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew check
  java10:
    name: Build with Java 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew check -xanimalsnifferMain -xanimalsnifferTest

  integration:
    name: Integration test
    needs: [java9]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew integrationTest

